name: 'Bankrupt issues'

on:
  workflow_dispatch:

jobs:
  bankrupt:
    if: github.repository_owner == 'vercel'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: corepack enable
      - name: 'Bankrupt issues & send notification to Slack'
        run: node ./.github/actions/next-repo-actions/dist/bankrupt/index.js
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
